version: '3.8'
services:
  winx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: winx
    restart: no
    ports:
      - '80:80'
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      BOT_TOKEN: ${BOT_TOKEN}
      GROUP_ID: ${GROUP_ID}
      STRING_SESSION: ${STRING_SESSION}
      OPENAI_TOKEN: ${OPENAI_TOKEN}
